name: openstoreapp_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.10.1 
  flutter_staggered_grid_view: ^0.3.0
  cloud_firestore: ^0.14.4
  carousel_pro: ^1.0.0
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.18.4+1
  url_launcher: ^5.1.1


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
